"""DLM v0.0007 -- the v0.0006 core plus the egress boundary.

v0.0006 was rebuilt from the first principle; v0.0005 is kept as a frozen
reference for the overall skeleton. v0.0006 implements only the core idea:

    recognize the general logic a natural-language sentence instantiates, make
    it explicit as a function-free Horn atom, and abstain when it cannot.

Module 1 is the semantic normal form -- the *target* of that conversion.
"""
from __future__ import annotations

from .logic import (
    Atom,
    Const,
    Frame,
    Literal,
    Rule,
    Schema,
    SchemaRegistry,
    Term,
    Var,
)
from .kb import DictStateGrounder, KnowledgeBase, StateBinding, StateGrounder
from .engine import Retriever, closure, entails, holds, prove
from .kernel import Proof, verify
from .unify import Subst, apply_atom, unify, walk
from .reader import (
    AGENT,
    DEFAULT_PREPOSITIONS,
    FIGURE,
    GROUND,
    PATIENT,
    SUBJECT,
    LexicalReader,
    Reader,
    tokenize,
)
from .convert import (
    Ingestor,
    form_to_logic,
    sentence_to_literal,
    sentence_to_literals,
    state_to_facts,
)
from .judge import (
    Adjudicator,
    Judgement,
    Judge,
    KbProposer,
    Policy,
    ProofJudge,
    Proposal,
    Proposer,
    StaticProposer,
    Verdict,
)
from .wire import (
    DlmService,
    WireError,
    WireService,
    render_choice,
    render_noul,
    render_score,
    systemone,
)
from .selfsup import (
    Example,
    FeatureScorer,
    Pair,
    RejectionSelfTrainer,
    ScorerRetriever,
    closure_mask_examples,
    compose_rules,
    evaluate,
    features,
    flip_labels,
    minimal_pairs,
    proof_cost,
    proof_holes,
    recall_at_k,
    rule_composition_examples,
    rule_removal_examples,
    scramble_constants,
    soundness,
    ssl_l_examples,
    train,
)
from .realize import (
    Bundle,
    CheckedRealizer,
    Realization,
    RealizedService,
    Realizer,
    TemplateRealizer,
    bundle_from_answer,
)
from .chat import (
    ChatRule,
    ChatScript,
    ChatSession,
    DEFAULT_SCRIPT,
    banner,
    chat_once,
    fill,
    match,
    random_elt,
    swap_pronouns,
)
from .sexp import (
    Form,
    SexpError,
    Sym,
    atom_to_form,
    dump,
    dump_all,
    form_to_atom,
    form_to_literal,
    form_to_rule,
    literal_to_form,
    parse,
    rule_to_form,
)

__version__ = "0.0.7"

__all__ = [
    "AGENT",
    "Adjudicator",
    "Atom",
    "Bundle",
    "ChatRule",
    "ChatScript",
    "ChatSession",
    "CheckedRealizer",
    "Const",
    "DEFAULT_PREPOSITIONS",
    "DEFAULT_SCRIPT",
    "DictStateGrounder",
    "DlmService",
    "Example",
    "FIGURE",
    "FeatureScorer",
    "Form",
    "Frame",
    "GROUND",
    "Ingestor",
    "Judge",
    "Judgement",
    "KbProposer",
    "KnowledgeBase",
    "LexicalReader",
    "Literal",
    "PATIENT",
    "Pair",
    "Policy",
    "Proof",
    "ProofJudge",
    "Proposal",
    "Proposer",
    "Reader",
    "Realization",
    "RealizedService",
    "Realizer",
    "RejectionSelfTrainer",
    "Retriever",
    "Rule",
    "SUBJECT",
    "Schema",
    "SchemaRegistry",
    "ScorerRetriever",
    "SexpError",
    "StateBinding",
    "StateGrounder",
    "StaticProposer",
    "Subst",
    "Sym",
    "TemplateRealizer",
    "Term",
    "Var",
    "Verdict",
    "WireError",
    "WireService",
    "apply_atom",
    "atom_to_form",
    "banner",
    "bundle_from_answer",
    "chat_once",
    "closure",
    "closure_mask_examples",
    "compose_rules",
    "dump",
    "dump_all",
    "entails",
    "evaluate",
    "features",
    "fill",
    "flip_labels",
    "form_to_atom",
    "form_to_literal",
    "form_to_logic",
    "form_to_rule",
    "holds",
    "literal_to_form",
    "match",
    "minimal_pairs",
    "parse",
    "proof_cost",
    "proof_holes",
    "prove",
    "random_elt",
    "recall_at_k",
    "render_choice",
    "render_noul",
    "render_score",
    "rule_composition_examples",
    "rule_removal_examples",
    "rule_to_form",
    "scramble_constants",
    "sentence_to_literal",
    "sentence_to_literals",
    "soundness",
    "ssl_l_examples",
    "state_to_facts",
    "swap_pronouns",
    "systemone",
    "tokenize",
    "train",
    "unify",
    "verify",
    "walk",
    "__version__",
]